client: rework Dial into DialEndpoint
SDK<->NeoGo circular dependency makes it impossible to roll out
40a203fdfebb87a837108a6762b61a63940921ce as is:

    # github.com/nspcc-dev/neo-go/pkg/services/helpers/neofs
    ../../go/pkg/mod/github.com/nspcc-dev/neo-go@v0.123.0/pkg/services/helpers/neofs/neofs.go:221:10: prmDial.SetContext undefined (type client.PrmDial has no field or method SetContext)
    ../../go/pkg/mod/github.com/nspcc-dev/neo-go@v0.123.0/pkg/services/helpers/neofs/neofs.go:223:11: prmDial.SetTimeout undefined (type client.PrmDial has no field or method SetTimeout)
    ../../go/pkg/mod/github.com/nspcc-dev/neo-go@v0.123.0/pkg/services/helpers/neofs/neofs.go:231:19: not enough arguments in call to c.Dial
            have (client.PrmDial)
            want (context.Context, client.PrmDial)

The only other option is fixing NeoGo and either using an unstable revision
of it (unacceptable) or making a release, but it's not ready for that either.

So this patch makes Dial() work the way it worked before, but introduces a new
simplified DialEndpoint() moving some options to PrmInit. Overall, this makes
New/DialEndpoint easier to use while solving the same #866 problem.

Signed-off-by: Roman Khimov <roman@nspcc.ru>